apiVersion: apps/v1
kind: Deployment
metadata:
  name: king
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: run 
  template:
    metadata:
      labels:
        app: run
    spec:
      containers:
        - name: naveen
          image: ramakrishna737/game:v1
          ports:
            - containerPort: 3000

